### ISSUE TITLE
Proxy / Templating locator error

### ISSUE THREAD

**Issue by lunetics** [mremi/TemplatingExtraBundle#1]
When i use this with https://github.com/javiereguiluz/EasyAdminBundle it throws some errors

I could narrow it down to the TemplatingProxy::startProfiling for the method:

(line 128) $this->templateLocator->locate($templateReference) 

The EasyAdminBundle uses a '@EasyAdmin/foo.html.twig' notation, which is not correctly parsed? 
I get an error that the template could not be found, with the TemplatingExtraBundle disabled it works.

**Comment by mremi** [comment]
Hi,

Can you give me the stack trace please?

**Comment by mremi** [comment]
No news, I close this issue.
